### PR TITLE
FEAT(docs): Add Tab Autocomplete guide and alternatives

### PR DESCRIPTION
**Pull request by charlwillia6**
- Introduce Ollama local models as another alternative
- Provide JSON configuration examples for Ollama models

image

### CODE REVIEW

**Review by ICEPrey — APPROVED** [review]

**Comment by jpan8866** [comment]
I suggest adding a step to clarify how to access the config file (see nang's blog on autocomplete: https://trypear.ai/blog/setting-up-auto-complete-on-pearai)

**Comment by Fryingpannn** [comment]
Yo would be great if can add screenshot 👀

**Comment by charlwillia6** [comment]
@Fryingpannn Screenshot added to the first comment of this PR, and pro-tip and screenshots added to tab-autocomplete.mdx.  Check out the screenshot!

**Comment by jpan8866** [comment]
Why was mdxPageComponent added? i think this is deprecated. The page doesn't render with plugin: `[ERROR] [Error [ValidationError]: "mdxPageComponent" is not allowed]`

seems to work fine without it however

**Comment by charlwillia6** [comment]
> Why was mdxPageComponent added? i think this is deprecated. The page doesn't render with this plugin, fails with error: `[ERROR] [Error [ValidationError]: "mdxPageComponent" is not allowed]`
> 
> seems to work fine without it however

@jpan8866 MDX pages are not deprecated and are a core part of Docusaurus. 

There were no warnings on my end. How did you get this warning? I also didn't receive any errors when I served it. 

The only reason I used mdx pages is so I could use HTML because I wanted to do things I couldn't with markdown. If you want me to change them back, I will. Let me know and I'll update the PR later today.

**Comment by jpan8866** [comment]
> > Why was mdxPageComponent added? i think this is deprecated. The page doesn't render with this plugin, fails with error: `[ERROR] [Error [ValidationError]: "mdxPageComponent" is not allowed]`
> > seems to work fine without it however
> 
> @jpan8866 MDX pages are not deprecated and are a core part of Docusaurus.
> 
> There were no warnings on my end. How did you get this warning? What steps? I also didn't receive any errors when I served it. Pages rendered fine for me.
> 
> The only reason I used mdx pages is so I could use JSX/HTML because I wanted to do things I couldn't with markdown. If you want me to change them back, I will. Let me know and I'll update the PR later today.

I pulled the changes and ran it locally, gives me the above error. I think the component should be added under the preset `pages` rather than `docs`, which makes the error go away for me. Anyhow I below mdxPageComponent is set to @theme/MDXPage by default, as even if I don't add this line, the .mdx file compiles just fine

**Comment by charlwillia6** [comment]
Updates have already been added.  PR is no longer needed.

**Pull request closed without merging**
